### ISSUE TITLE
compile issuel

### ISSUE THREAD

**Issue by Akua1919** [diegoroyo/mitsuba2#1]
- [🔨 compilation issue]

## Summary

I got compile errors  when I followed the documentation, but it works well if compile the officially original one.

## System configuration

- Platform: Windows 11/ Ubuntu 22.04 LTS
- Compiler: VS 2022/ clang 14.0
- Python version: 3.9/ 3.9
- Mitsuba 2 version: v2.2.1-nlos1.1
- Compiled variants:
    * `scalar_rgb`
    *  `packet_mono`

## Description

As above, when compiling, many errors about datatype occur, it is quite unreasonable.
Mainly, may I have the information about your system configuration as a reference?
Thanks a lot！

**Comment by diegoroyo** [comment]
Please use the [latest 1.2 release](https://github.com/diegoroyo/mitsuba2-transient-nlos/releases/tag/v2.2.1-nlos1.2), with the `scalar_rgb` variant. We will try to look into the `packet_mono` variants.

If you have more compile issues, feel free to reply
