### ISSUE TITLE
Three minor questions about this code

### ISSUE THREAD

**Issue by Enigmatisms** [diegoroyo/mitsuba2#2]
Hi! I've been following the works of your group and recently shifted my focus from BunnyKiller to mitsuba2-transient-nlos, and about this code I have three minor questions mainly and I'd appreciate it if you can answer these questions for me:
##### Medium support for transient path sampling
In `transientpath.cpp` there is a function called `sample`, which I believe it's for obtaining the transient time samples. It overrides the virtual function defined in class `TransientSamplingIntegrator`. However, the implementation in `transientpath.cpp` (from line 197) is:
```c++
void sample(const Scene *scene, Sampler *sampler, const RayDifferential3f &ray_,
           const Medium * /* medium */,
           std::vector<FloatSample<Float>> & /* aovs_record */,
           std::vector<RadianceSample<Float, Spectrum>> &timed_samples_record,
           Float max_path_opl, Mask active) const override {
```
and **medium** seems not get used at all. Also, the logic in this function seems to only have considered surface interactions but not medium interaction. So I wonder: Do I have any misunderstanding here and your code actually supports transient path sampling with medium? Or the code actually does not support medium interaction? If so, will this feature be added in the code or if I was to implemented this functionality **myself** just by referring to the original `volpath.cpp` and your code, is it tractable? I think this is a very  important feature (BK and mitsubaToF both have this functionality).

##### Mutex problem
In `streakfilm.cpp`, line 126-127. `global_max_opl` and `global_min_opl` are two global variables (might be modified by multiple threads):
```c++
/* Critical section: update min/max OPL */ {
     global_max_opl = std::max(global_max_opl, local_max_opl);
     global_min_opl = std::min(global_min_opl, local_min_opl);
}
```
Why there is no mutex to lock these variables just like what is done in line 132-134 (right below it)? These two variables are not atomic and min/max are not atomic neither. Is this some special feature in enoki or there is other reason behind this?

##### mitsuba3
Do you have any plan to opt for mitsuba3 since mitsuba 2 is no longer maintained? I lack good understanding of those algorithm and the experience of enoki and drjit, therefore though I really wanna try moving the transient-imaging and NLOS related code of yours to mitsuba3, there seems to be major refactoring work in here...

**Comment by diegoroyo** [comment]
Thanks for the interest in our work :) In order:

##### Medium support for transient path sampling

The current code for `transientpath.cpp` does not support medium interaction. It would be nice to have, but our current focus work does not require medium interaction and thus we do not currently plan to support it.

If you plan to add support for medium interactions, I think you should only need to modify the integrator and nothing else. You can modify `volpath.cpp` and, instead of returning a `std::pair<Spectrum, Mask>`, you should add a `RadianceSample<Float, Spectrum>` to `timed_samples_record` as in `transientpath.cpp` every time you find a light source, and keeping track of the path travel distance similar to what `path_opl` does.

You can add this functionality in a new integrator or you can extend `transientpath.cpp` to support it. A pull request would be very welcome (and of course, credited). If you need help with the current code do not hesitate to ask.

##### Mutex problem

I think that is a bug, thank you for spotting it and reporting it :) There should be a `std::lock_guard<std::mutex> lock(mutex);` as in the critical section below. I'll update the code shortly.

##### mitsuba3

Yes, we have plans to move to mitsuba3. Some work has been done, but this is a large change and it is not high priority for us at the moment. Hopefully in the near future I can give an update with this :)

**Comment by Enigmatisms** [comment]
Thank you!

**Comment by Enigmatisms** [comment]
Also, I have noticed that in both mitsuba2 and mitsuba3's docs: 
> **Bidirectional path tracing**: to be added. **Progressive photon mapping**: to be added.

So when I tried to understand how the path tracing is done, it seems that mitsuba2 and mitsuba3 only trace path from sensor and let it bounce util it samples an emitter? This is reasonable for area emitter, but is this kind of approach efficient in NLOS? Shouldn't the emitter of nlos problem be a laser which should be a collimated point source? I assume it's gonna be extremely noisy if there is no bidirectional path tracer. So how do you achieve efficient laser sampling? I kind of make me think that I should fallback to BunnyKiller again, since I need to sample from a laser source... Here is what the doc says:
> Path-space MCMC techniques were an incredibly complex component of the previous generation of Mitsuba. We do not currently plan to port these and recommend that you stick with Mitsuba 0.6 if your application depends on them.

**Comment by Enigmatisms** [comment]
So I this is what I found:
> nlos scenes only have one laser emitter - standard emitter sampling techniques do not apply as most directions do not emit any radiance, it needs to be very lucky to bsdf sample the exact point that the laser is illuminating. this modifies the emitter sampling so instead of directly sampling the laser we sample (1) the point that the laser is illuminating and then (2) the laser

I'm guessing the efficient sampling is done by (sort of) converting the collimated laser to an area emitter? (the relay wall being the emitter instead of the laser itself)?

**Comment by diegoroyo** [comment]
One of the main points of this project was to develop sampling techniques that were efficient in NLOS scenes. As you said, it is very hard to sample a collimated point source using default mitsuba2/mitsuba3. We developed laser sampling, which converts the collimated laser to a virtual point light source located on the relay wall, which can be sampled from any point in the geometry. This is not exactly the same as done in BunnyKiller, but pretty similar. This technique greatly speeds up the convergence of the algorithm in NLOS scenes.

For a more in-depth explanation, you can read our work mentioned in the README (Non-line-of-sight transient rendering). If you just want to use it, you can set `nlos_laser_sampling` to `true`:
```xml
<scene version="2.2.1">
   <integrator type="transientpath">
      <boolean name="nlos_laser_sampling" value="true"/>
      ...
   </integrator>
   ...
```

**Comment by Enigmatisms** [comment]
Then I think there is no simple work around for collimated laser sampling in the media since I can not convert it to any kind of simple light source. This solves my confusion, thank you.

**Comment by diegoroyo** [comment]
If it helps you, the [`emitter_laser_sample`](https://github.com/diegoroyo/mitsuba2-transient-nlos/blob/feat-transient/src/integrators/transientpath.cpp#L70) function in `transientpath.cpp` works exactly the same as sampling a point light source such as next-event estimation in [`emitter_nee_sample`](https://github.com/diegoroyo/mitsuba2-transient-nlos/blob/feat-transient/src/integrators/transientpath.cpp#L38).

I'm not that familiar with participating media, but if you can sample from a point light source I think you should be able to sample a collimated laser too. If not, I can give some help if necessary.

**Comment by G-nn-r** [comment]
> Yes, we have plans to move to mitsuba3. Some work has been done, but this is a large change and it is not high priority for us at the moment. Hopefully in the near future I can give an update with this :)

I just wanted to mention that I'd be really interested in a transient version of Mitsuba3. If you have any news or approximate timeframes, that would be highly appreciated!

**Comment by Enigmatisms** [comment]
Making an equivalent light source is indeed a workaround for sampling a collimated laser source. So, with the same idea, if I can find a way to convert the incident point on the participating medium according to its phase function and some basic geometric optics like refraction and reflection, there might be a way to convert the collimated laser to a complex point source (an anisotropic one). So what do you think? Just like what's done in [emitter_laser_sample](https://github.com/diegoroyo/mitsuba2-transient-nlos/blob/feat-transient/src/integrators/transientpath.cpp#L70), special method of sampling at the boundary of the participating medium might be developed, thus an equivalent light source may be created.
Yet, careful consideration should be made, and it's going to be some time until I can do some coding about this, since I am not so familiar with mitsuba.
